### ISSUE TITLE
Ajuda com Lista 3

### ISSUE THREAD

**Issue by tailineju** [tailineju/SHINY-tutorial#1]
Lista 3........

**Comment by gabimonteiiroo** [comment]
O slide já está pronto?

**Comment by ghost** [comment]
@gabimonteiiroo , você pode me ajudar?

**Comment by gabimonteiiroo** [comment]
@daviguerraa, com o que? Pede pro @AruomnosdaJ te ajudar, estou muito ocupada.

**Comment by AruomnosdaJ** [comment]
Se for sobre o assunto da lista é melhor pedir para o @eduardoleopoldinogoncalves .

**Comment by eduardoleopoldinogoncalves** [comment]
Sei não, acho melhor perguntar para @tailineju .

**Comment by AruomnosdaJ** [comment]
Só falta o @Guilherme-Souza-Rodrigues  dizer se tá certo?

**Comment by Guilherme-Souza-Rodrigues** [comment]
Tá certo! Bom trabalho!

**Comment by Guilherme-Souza-Rodrigues** [comment]
Missão cumprida!
